In [1]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [2]:
df= pd.read_csv("/Users/himanshunautiyal/Desktop/untitled folder/Project/data/raw/10_benchmark_indices.csv")

In [3]:
df.head()

         date index_name  close_value
0  2022-01-03    NIFTY50     17492.79
1  2022-01-04    NIFTY50     17689.64
2  2022-01-05    NIFTY50     17835.05
3  2022-01-06    NIFTY50     17878.51
4  2022-01-07    NIFTY50     17759.15

In [4]:
df.sample()

            date index_name  close_value
5485  2025-05-26   NIFTY500     27532.55

In [5]:
df.dtypes

date            object
index_name      object
close_value    float64
dtype: object

In [6]:
df["date"] = pd.to_datetime(df["date"])

In [7]:
df.dtypes

date           datetime64[ns]
index_name             object
close_value           float64
dtype: object

In [10]:
## Checking for the duplicated rows
df.duplicated().sum()

np.int64(0)

In [11]:
## droping the duplicated rows
df.drop_duplicates(inplace=True)

In [12]:
df.to_csv("/Users/himanshunautiyal/Desktop/untitled folder/Project/data/processed/10_cleaned_benchmark_indices.csv",index=False)